// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.API.Data;

#nullable disable

namespace Movies.API.Migrations
{
    [DbContext(typeof(MoviesAPIContext))]
    [Migration("20240205021248_SeedMovieTableToDb")]
    partial class SeedMovieTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movies.API.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Drama",
                            ImageUrl = "images/src",
                            Owner = "alice",
                            Rating = "9.3",
                            ReleaseDate = new DateTime(1994, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Crime",
                            ImageUrl = "images/src",
                            Owner = "alice",
                            Rating = "9.2",
                            ReleaseDate = new DateTime(1972, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            ImageUrl = "images/src",
                            Owner = "bob",
                            Rating = "9.1",
                            ReleaseDate = new DateTime(2008, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Crime",
                            ImageUrl = "images/src",
                            Owner = "bob",
                            Rating = "8.9",
                            ReleaseDate = new DateTime(1957, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "12 Angry Men"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Biography",
                            ImageUrl = "images/src",
                            Owner = "alice",
                            Rating = "8.9",
                            ReleaseDate = new DateTime(1993, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Drama",
                            ImageUrl = "images/src",
                            Owner = "alice",
                            Rating = "8.9",
                            ReleaseDate = new DateTime(1994, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Drama",
                            ImageUrl = "images/src",
                            Owner = "bob",
                            Rating = "8.8",
                            ReleaseDate = new DateTime(1999, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Romance",
                            ImageUrl = "images/src",
                            Owner = "bob",
                            Rating = "8.8",
                            ReleaseDate = new DateTime(1994, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
